### ISSUE TITLE
'plugins/vis-ultisnips/init.snipmate-parser' not found

### ISSUE THREAD

**Issue by thinlines** [machinedgod/vis-ultisnips#11]
Hi!

With `vis 0.7` and the following `visrc.lua`:

```lua
-- load standard vis module, providing parts of the Lua API
require('vis')

local plug = require('vis-plug')

local plugins = {
	{ 'machinedgod/vis-ultisnips', alias = 'mysnips' },
}

plug.init(plugins, true)

-- access plugins via alias
plug.plugins.mysnips.snipmate  = '/home/randy/.config/vis/vim-snippets/snippets/'
plug.plugins.mysnips.ultisnips = '/home/randy/.config/vis/vim-snippets/UltiSnips/'

vis.events.subscribe(vis.events.INIT, function()
	-- Your global configuration options
end)

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
	-- Your per window configuration options e.g.
	-- vis:command('set number')
end)
```

The plugin can't seem to find `snipmate-parser` or `ultisnips-parser`. If I move them into `init/` in the `vis-ultisnips` project directory, the error goes away.  The problem seems to be with `cwd = ...` in `init.lua`. I reckon this is possibly an issue with Lua version or `vis-plug`.
I have Lua 5.3 and Lua 5.4 on my system (Arch Linux), but I don't know which one `vis` is using.

I made sure `vis-plug` and `vis-ultisnips` were up to date with a `git pull`.
 
This doesn't seem like a major issue and I've already found a solution that I'm satisfied with, but I figured I'd submit a report in case it helps.

Thanks for developing this plugin!

**Comment by thinlines** [comment]
If I load `vis-ultisnips` without `vis-plug` &mdash; as in `local snips = require('vis-ultisnips')`, the issue goes away, too. This seems to suggest it's an issue with `vis-plug`, not `vis-ultisnips`. Strange!

**Comment by machinedgod** [comment]
Hey!
Thanks for the report. I think the issue is that the `plug.init` of `vis-plug` only /declares/ the plugins. You have to install them by executing `plug-install` once, inside vis. Thing is, the first time vis is ran with new plugin declared - .visrc is ran before you have the chance to install plugins (I think this can be configured in vis-plug, btw!), the configuration part is also ran and files haven't been downloaded.

Attempt the `:plug-install` once inside vis. The plugin manager should download and store the files in `.cache/vis-plug` by default.

Either way, its a good catch - setting up configuration before having a chance to install the plugin isn't the best idea, I'll think of something better.

**Comment by thinlines** [comment]
Sorry for not replying! I don't remember why I didn't reply, but you wrote a very kind and helpful response, so I apologize. Thank you for your help!

**Comment by machinedgod** [comment]
Nothing to apologize about buddy, at all.

I'm doing some long overdue improvements and its now far more usable, I hope you're finding it useful still. Need to squash couple of bugs and it should be right at the point where I want it to be :)

Have a wonderful rest of the day.
